---
- name: enable 'Install updates for other Microsoft Products'
  win_regedit:
    path: "{{ item.path }}"
    name: "{{ item.name }}"
    type: "{{ item.type }}"
    data: "{{ item.data }}"
  with_items:
    - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Services', type: string, name: DefaultService, data: 7971f918-a847-4430-9279-4a52d1efe18d }
    - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Services\7971f918-a847-4430-9279-4a52d1efe18d', type: dword, name: RegisteredWithAU, data: 1 }
  when: WINDOWS_UPDATE_OTHER_MS_PRODUCTS

- name: install windows updates
  win_updates:
    category_names: "{{ WINDOWS_UPDATE_CATEGORIES }}"
    state: installed
    reboot: "{{ windows_reboot_allowed }}"
    reboot_timeout: 9000
  when: windows_update_allowed
  register: win_update_result
  changed_when:
    - win_update_result.installed_update_count is defined
    - win_update_result.installed_update_count > 0
  failed_when:
    - win_update_result.failed_update_count is defined
    - win_update_result.failed_update_count > 0
